spring:
  servlet:
    multipart:
      max-file-size: 1000MB # 最大支持文件大小
      max-request-size: 5000MB # 最大支持请求大小

dist:
  oss:
    config:
      enabled: true  # 默认true
      secure: false  # 是否启动 https 访问, 默认 false
      endpoint: http://127.0.0.1
      port: 9000
      accessKey: ossadmin
      secretKey: ossadmin
      default-bucket: default # 可选，仅支持小写字母,长度必须大于3个字符,默认桶会自动创建
